export default function TermsPage() {
  return (
    <main className="mx-auto w-full max-w-3xl flex-1 px-4 py-12 sm:px-6 sm:py-16">
      <header className="mb-10 text-center">
        <h1>Terms and Conditions</h1>
      </header>
			  <h2> Section One</h2>
			
      <div className="rounded-3xl border border-border/60 bg-background/70 bg-gradient-to-b from-white/[0.06] to-transparent p-8 shadow-[inset_0_1px_0_0_rgba(255,255,255,0.08),0_24px_48px_-12px_rgba(0,0,0,0.5)] backdrop-blur-xl sm:p-12">
        <div className="text-muted-foreground space-y-6">
		<h3> AI statement regarding rights. </h3> 
          <p>
            This is in plain english as we're not a lawyer. Your content, that you choose to bring to us to collaborate upon, and iterate within the confines of this project - is NOT going to be sold to any third party. There will be no open source training on content. As there will be no generative media content within this project, and the only content touched by AI is very little of the code...  There is no training, there is OPEN SOURCE FREE training either. Your content will remain FREE of any singular corporation or individual somehow wanting to train on your content.  Sadly as it is, once it is out on the internet, I cannot prevent what corporations and insidious individuals do with whatever they find via Youtube or Discord servers in general. As someone with a background in design AND tech influences, we are doing our best to keep your content safe and secure.
          </p>
			 <h3> Storage </h3> 
          <p>
            As of right now, the only places that your files end up after you send them are a private discord that is shared by Earthnicity, Us (Duskfallcrew) and OTNAngel. This is because we run Under Rug Swept Misfits (formerly Earth and Dusk), and we live at opposite ends of the planet from each other. We are very much unsure of how to handle uploaded data outside of discord, and so we're not sure at this stage if we are interested in handling data outside of private sharing. If we can promise that a cloudflare bucket is safe enough, we may set up an upload/volunteer audition section.  We do NOT wish to store the flat WAV or m4a files anywhere in such way that could be used for other purposes. Public viewing of your voice or content, is only in the youtube and tiktok or social media videos that are created. 
          </p>
			<h3> Other Collaboration</h3> 
		   <p>
            If you are providing collaboration outside of your voice, and are concerned about the terms and rights etc of your content you share within this project this part is again in painfully plain english as we are not a lawywer. Anything that you provide to us either in future based on the cloudflare concept as stated above, OR via discord private sharing - is never shared with a third party in terms of business or AI training. The only third party would be classified as other people involved with the project. We will not openly provide nor share in public any images, bones or other files that pertain to your invovlement. We are not responsible however if you share your content in public spaces related to the project, as no matter how many rules we set in a public discord, or in the case of a hashtag on social media - people are instinctivly immature in this case. The content you provide in private stays private until it is rendered within the project as a final file.   
          </p>
        </div>
      </div>
			  <h2> Section Two </h2>
	  <div className="rounded-3xl border border-border/60 bg-background/70 bg-gradient-to-b from-white/[0.06] to-transparent p-8 shadow-[inset_0_1px_0_0_rgba(255,255,255,0.08),0_24px_48px_-12px_rgba(0,0,0,0.5)] backdrop-blur-xl sm:p-12">
        <div className="text-muted-foreground space-y-6">
		<h3> Project Copyright </h3> 
          <p>
           We operate under a largely open source delegation for a lot of things that we do. However the only thing that we need to legally distinguish here is the parts that we legally own as not just indivduality is at risk here, but also the fact that you legally cannot claim certain things about us. While you can and are able to remix, reuse concepts of the characters of sorts within this world, you cannot lay claim to them as a whole. You have to legally remember that this is a project based on an individual who has Dissociative Identity disorder, and legally trying to claim copyright over alters is probably an extremely stupid idea. Also, someone already tried to do this in 2023, and tried to tell me in australian swearing language to go eff myself. Inspiration is absolutely fair and valid, but if you're going to copy more than just a few concepts - we do require credit. We do NOT require royalty fees or anything like that. You cannot really copyright a whole headspace, it is mostly just an addendum to tell you that you cannot really copyright our identity but you are welcome to be inspired and remix and go forth. 
			
          </p>
			   <h3> General Conditions </h3> 
          <p>
            We do have some basic legal copyright that covers the BASIS of the project. We are heavily aware of the fact that normally, games like this are subject to a staunch no-modification policy. Within rights, however this specific game sort of acts on a fight club status. The more creative you are, the less Daddy's gonna get the grandparents from corporate down to smite you. The point of this project is to act within the cultural boundaries of this copyrighted content. Nothing in this should in theory break the terms and conditions itself of Final Fantasy XIV.  If we were able to attend a fan-fest, we indeed would actually submit this project for review by the staff in some format or another. We are aware yes, though that we would likely be unable to be publically showing this off at a fanfest like an AMV or otherwise, as we are unsure how that sort of thing works for heavily modded content. Anything that borders NSFW is on a pg-13 basis, and nothing borders a heavier R rating. This clearly is a basis of opinion based on cultural background, but we ascertain this rating based on what basic stuff is already on the almost too sexy side in Final Fantasy XIV.
          </p>
		  <p>
            An absolute example of this is Kay Solas, his outfit that is not his healer outfit - or at least the one that's least covered because it is from Arcadion, is the PVP gear from a few seasons ago mixed with custom baggy pants that border on the edge of pg-13. It would be considerably a questionable PG-13 to some, but nothing is showing that would cause that rating to literally move in the terms of how movie ratings used to go. Now we are entirely aware that this does not fly with everyone. 
          </p>
		  
		 
		    </div>	
		
        </div>
		
		   <h2> Section Three</h2>
	  <div className="rounded-3xl border border-border/60 bg-background/70 bg-gradient-to-b from-white/[0.06] to-transparent p-8 shadow-[inset_0_1px_0_0_rgba(255,255,255,0.08),0_24px_48px_-12px_rgba(0,0,0,0.5)] backdrop-blur-xl sm:p-12">
        <div className="text-muted-foreground space-y-6">
		 	<h3> Content Warnings </h3> 
			 <p> We understand multiple levels of diversity alone within the mental health community.  While we try and do our best to understand, grasp and limit any issues within the context of warnings, triggers and otherwise we cannot plan for every singular event. The purpose of this project is to sort of dance around the hardest of our topics, fictionalize it so it's a creative outlet. This part may seem like it is romanticizing our issues, and it is never intended to. While it is incredibly for fictional and story reasons interesting to be as cracked as possible, being physically and metally as ill as some of the topics touched on - it is never something we wish on anyone else.  We may not have things AS severe as other people, as other systems, as other diagnosed or self, or undiagnosed individuals. However, our story is ours, but the caveat is that if anything may need a more proper content warning previous to a beginning an episode or a section in one of these site pages, we would hope that with understanding - the community could aid us. We ourselves try not to limit every single piece of media consumed based on our trauma, as we feel sometimes exposure can aid. This sometimes can be extremely stupid, and we also note that we have seizures from CPTSD because jokingly we call ourselves unintelligent in the moment because we expose things sometimes at the wrong times. If something in this project is too much, and it is far beyond a content warning, we do promote the idea of stepping away safely, and letting yourself breathe. We do not want to harm anyone, and we try and limit the amount of severe topics that would even trigger us. Please let us know via one of our contact channels if something is bothering you in regards to content warnings and triggers. This does not cover anyone getting fandom-triggered and eye-twitching over our alters being dipshits about Miqo naming conventions.       </p> 
		  
		  <h3> Cultural Responsibility </h3> 
		  
		    <p> This is a section that is not really for legal purposes but can still be classified as such. YOU CANNOT under any legal circumstances gatekeep the content within this project. You can legally suggest, guide and give education on how something could go better. One of the reasons for this statement is because a few of our alters which are characters in this series are not of the same skin color NOR background as the body. Cultural context is gathered and guessed based on context clues of either their in system experiences or our own body experiences based on our location of where we have lived for twenty five or more years. We are a system that tends to operate under the assumption that we are so white that even the whites get mad when we show up. However, we respect as much as we are physically and mentally able to the cultures that are adjacent to this project. IF anything, for example Cameron's heritage is Black/South African. We have a surface level understanding about Afrikaans, as well as SOME historical knowledge of the country of south africa. This is not due to any hyperfixation, it is literally that as a physical meatsuit we have lived in New Zealand off and on since 1999. We have known people from there, and we have learned things about their culture to a small amount, and we have at least once attended a sports ball game related to said country. Granted it was back when Carisbrook still existed, and it was All Blacks vs South Africa back when it was the Tri-Nations games. 			</p>
			<p>  As for the question of validity of the color and heritage of those claiming to be from Osea, this is an odd question to be able to understand an answer for.  We cannot under any circumstance claim this race exists in literal time. What alters feel is a different kettle of fish, and legally we would not sit there and claim we were physically from there. Not because of a disorder or any claim, but because it would almost erase the struggles of mirrored cultures. Osea is a feeling, a memory to those that have them in the system, and while the idea of plausibly lived in another time in place is a reality to a point, it does not give legal right for our body to claim certain things.  We are so white that we look at our DNA test and hide under the table, make apologies to the celtic tribes, make apologies to the Irish, the Scottish, the Germans and shit- we even make apologies for Elon Musk. Why? Because sadly we are actually fucking related to that ass-hat.  His mother's line shares a surname with our birth family on my fathers side, and while they are valid human beings, I do not have to make any apologies for how I feel about what is going on politically in life. </p> 
   <h3> Political Responsbility </h3> 
<p>			Beyond that you can be absolutely damn sure I will not make huge political waves within this project as it is not my responsibility to act as old man/person yelling at clouds. That is because the idea of politics is under the content warning guidelines section, and a cultural responsibility at the same time. Politics are messy, and while we ascertain that we are largely left wing and ecological to a point - we are not going to put lines in a sandbox to prevent everyone from seeing our content. We will not use our platform for this project for HEAVY intereaction with politics. That being said, political is a strong and wide subject. We will not be silent on issues that are not widely considered political to us, and things like our mental health, our gender identity are not political. Nor are human rights, so if you are reading this Ed Sheeran - Free Palestine. Apart from that, our platform is not to be used to demean anyone. Humor and fun are entirely within rights, but we will do our best not to dive into the absolute stupidity that we cannot come back from.  The responsibility on this is not to anger ourselves, trigger ourselves, as well as not start absolute content-driven wars on the internet. If you or someone you love are against 99% of what this project stands for, we do legally ask you nicely step away before you leave a nasty comment in one of our videos. While we add that everyone is welcome, everyone is not welcome to start world war ten in the comments section. It does not matter to a point what party or whatever you vote for, if you are here to enjoy a creative project and you plan to behave like an adult, you are welcome here.  Discussion, debate are adult ways of handling things that you do not agree with, and we validate that. Be aware that we cannot, and will not be able to adhere to every minute detail of every section that one may require.  </p>
			    </div>
      </div>
    </main>
  );
}

